const MAPBOX_API_KEY = process.env.NEXT_PUBLIC_MAPBOX_API_KEY as string
const MAPBOX_USERID = process.env.NEXT_PUBLIC_MAPBOX_USERID as string
const MAPBOX_STYLEID = process.env.NEXT_PUBLIC_MAPBOX_STYLEID as string
const API_ENDPOINT = process.env.API_ENDPOINT as string

export { MAPBOX_API_KEY, MAPBOX_USERID, MAPBOX_STYLEID, API_ENDPOINT }
