const MAPBOX_API_KEY = process.env.NEXT_PUBLIC_MAPBOX_API_KEY
const MAPBOX_USERID = process.env.NEXT_PUBLIC_MAPBOX_USERID
const MAPBOX_STYLEID = process.env.NEXT_PUBLIC_MAPBOX_STYLEID
const API_ENDPOINT = process.env.API_ENDPOINT

export { MAPBOX_API_KEY, MAPBOX_USERID, MAPBOX_STYLEID, API_ENDPOINT }
